/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OutputFrame.java
 *
 * Created on Dec 7, 2011, 9:06:10 PM
 */

package org.clothocad.tool.ResDigest;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Hashtable;
import javax.swing.JOptionPane;

/**
 *
 * @author rishi
 */
public class OutputFrame extends javax.swing.JFrame {

    /** Creates new form OutputFrame */
    public OutputFrame() {
        initComponents();
        
    }

    public OutputFrame(String s)
    {
        this();
        this.setTitle(s);
        this.JEditorPaneplasmidViewer.setText("<html><font color=\"red\">hello world!</font></html>");
    }

    
    public void writeToPlasmidViewer(String s, Hashtable enz)
    {
        Enumeration keys = enz.keys();
        while (keys.hasMoreElements())
        {
            String enzyme = (String)keys.nextElement();
            String value = (String)enz.get(enzyme);
            String[] w = value.split("\\s+");
            String pattern=null;
            if (w.length==2 || w.length==1) pattern = w[0];
            else pattern = w[1];
            pattern = pattern.replaceAll("\\*", "");
            String regex = pattern.replaceAll("N", "[a-zA-Z]");
            regex ="\\["+enzyme+"\\]"+regex;
            pattern = "\\["+enzyme+"\\]"+pattern;
            
            s=s.replaceAll(regex,"<font color=\"red\">"+pattern+"</font>" );
        
        }
        String out = "<html>"+s+"</html>";
        this.JEditorPaneplasmidViewer.setText(out);
    }
    /**deprecated function
    public void writeToPlasmidViewer(String s, ArrayList<String> matches)
    {
        String out="";
        //converting brackets to # to avoid confusion in regex!
        s = s.replaceAll("\\(", "#");
        s = s.replaceAll("\\)", "#");
        for (int i = 0; i < matches.size(); i++)
        {
            String m = matches.get(i).replaceAll("\\(", "#");
            m = m.replaceAll("\\)", "#");
            s = s.replaceAll(m,"<font color=\"red\">"+matches.get(i)+"</font>");
        }
        out = "<html>"+s+"</html>";
        this.JEditorPaneplasmidViewer.setText(out);
    }
   
    **/
    
    public void writeOutput(boolean hasResult, ArrayList<String> frags, ArrayList<String> enzymes, ArrayList<String> locations)
    {
        String output ="";
        if (!hasResult)
        {
            this.jTextAreaOutput.setText("Sorry, none of the selected enzymes can be mapped on the plasmid!!");
        }

        else
        {
           for (int i = 0; i < enzymes.size(); i ++)
           {
               if (locations.get(i).length() > 2) //only show enzyme if it has been used
                output+="\nEnzyme  : "+enzymes.get(i)+ "\nRestriction site locations: "+locations.get(i)+"\n";
           }
           output+="\n Total number of fragments : "+frags.size()+"\n";
           output+="\n\n*****************************RESULTS FROM VIRTUAL DIGEST***************************************************\n\n ";
           for (int i =0; i < frags.size(); i++)
           {
               output+=frags.get(i).length()+" : "+frags.get(i)+"\n\n";
           }


           this.jTextAreaOutput.setText(output);

        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JEditorPaneplasmidViewer = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JEditorPaneplasmidViewer.setContentType(org.openide.util.NbBundle.getMessage(OutputFrame.class, "OutputFrame.JEditorPaneplasmidViewer.contentType")); // NOI18N
        jScrollPane1.setViewportView(JEditorPaneplasmidViewer);

        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setLineWrap(true);
        jTextAreaOutput.setRows(5);
        jScrollPane2.setViewportView(jTextAreaOutput);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(OutputFrame.class, "OutputFrame.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(OutputFrame.class, "OutputFrame.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane JEditorPaneplasmidViewer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaOutput;
    // End of variables declaration//GEN-END:variables

}
