/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.clothocad.tool.blasto;

import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.*;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author cassie
 */
public class blastoGUI extends javax.swing.JFrame {

    /**
     * Creates new form blastoGUI
     */
    public blastoGUI() {
        super();
        //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Eugene IDE");
        this.setResizable(true);
        fc = new javax.swing.JFileChooser();
        /*
         * set bottonPane as message console
         */
        this.setVisible(true);
        initComponents();
        initMenu();
    }

    private void initMenu() {
        // add cut copy paste in edit menu
        cutMenuItem = new JMenuItem(new DefaultEditorKit.CutAction());
        cutMenuItem.setText("Cut");
        cutMenuItem.setMnemonic(KeyEvent.VK_T);
        editMenu.add(cutMenuItem);

        copyMenuItem = new JMenuItem(new DefaultEditorKit.CopyAction());
        copyMenuItem.setText("Copy");
        copyMenuItem.setMnemonic(KeyEvent.VK_C);
        editMenu.add(copyMenuItem);

        pasteMenuItem = new JMenuItem(new DefaultEditorKit.PasteAction());
        pasteMenuItem.setText("Paste");
        pasteMenuItem.setMnemonic(KeyEvent.VK_P);
        editMenu.add(pasteMenuItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        seq1TextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        seq2TextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        blastTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        blastnButton = new javax.swing.JButton();
        blast2seqButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        outputNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        seq1OpenButton = new javax.swing.JButton();
        seq1ImportButton = new javax.swing.JButton();
        seq2ImportButton = new javax.swing.JButton();
        seq2OpenButton = new javax.swing.JButton();
        seq1NameTextField = new javax.swing.JTextField();
        seq2NameTextField = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        seq1Menu = new javax.swing.JMenu();
        seq1OpenMenuItem = new javax.swing.JMenuItem();
        seq1ImportMenuItem = new javax.swing.JMenuItem();
        seq2Menu = new javax.swing.JMenu();
        seq2OpenMenuItem = new javax.swing.JMenuItem();
        seq2ImportMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        blastMenu = new javax.swing.JMenu();
        blastnMenuItem = new javax.swing.JMenuItem();
        blast2seqMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.title")); // NOI18N

        seq1TextArea.setColumns(20);
        seq1TextArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        seq1TextArea.setLineWrap(true);
        seq1TextArea.setRows(5);
        jScrollPane3.setViewportView(seq1TextArea);

        seq2TextArea.setColumns(20);
        seq2TextArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        seq2TextArea.setLineWrap(true);
        seq2TextArea.setRows(5);
        jScrollPane4.setViewportView(seq2TextArea);

        blastTextArea.setColumns(20);
        blastTextArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        blastTextArea.setRows(5);
        jScrollPane5.setViewportView(blastTextArea);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.jLabel3.text")); // NOI18N

        blastnButton.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.blastnButton.text")); // NOI18N
        blastnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blastnButtonActionPerformed(evt);
            }
        });

        blast2seqButton.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.blast2seqButton.text")); // NOI18N
        blast2seqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blast2seqButtonActionPerformed(evt);
            }
        });

        exportButton.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.exportButton.text")); // NOI18N
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        outputNameTextField.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.outputNameTextField.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.jLabel4.text")); // NOI18N

        seq1OpenButton.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq1OpenButton.text")); // NOI18N
        seq1OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seq1OpenButtonActionPerformed(evt);
            }
        });

        seq1ImportButton.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq1ImportButton.text")); // NOI18N
        seq1ImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seq1ImportButtonActionPerformed(evt);
            }
        });

        seq2ImportButton.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq2ImportButton.text")); // NOI18N
        seq2ImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seq2ImportButtonActionPerformed(evt);
            }
        });

        seq2OpenButton.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq2OpenButton.text")); // NOI18N
        seq2OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seq2OpenButtonActionPerformed(evt);
            }
        });

        seq1NameTextField.setEditable(false);
        seq1NameTextField.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq1NameTextField.text")); // NOI18N

        seq2NameTextField.setEditable(false);
        seq2NameTextField.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq2NameTextField.text")); // NOI18N

        fileMenu.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.fileMenu.text")); // NOI18N

        seq1Menu.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq1Menu.text")); // NOI18N

        seq1OpenMenuItem.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq1OpenMenuItem.text")); // NOI18N
        seq1OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seq1OpenMenuItemActionPerformed(evt);
            }
        });
        seq1Menu.add(seq1OpenMenuItem);

        seq1ImportMenuItem.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq1ImportMenuItem.text")); // NOI18N
        seq1ImportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seq1ImportMenuItemActionPerformed(evt);
            }
        });
        seq1Menu.add(seq1ImportMenuItem);

        fileMenu.add(seq1Menu);

        seq2Menu.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq2Menu.text")); // NOI18N

        seq2OpenMenuItem.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq2OpenMenuItem.text")); // NOI18N
        seq2OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seq2OpenMenuItemActionPerformed(evt);
            }
        });
        seq2Menu.add(seq2OpenMenuItem);

        seq2ImportMenuItem.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.seq2ImportMenuItem.text")); // NOI18N
        seq2ImportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seq2ImportMenuItemActionPerformed(evt);
            }
        });
        seq2Menu.add(seq2ImportMenuItem);

        fileMenu.add(seq2Menu);

        jMenuBar1.add(fileMenu);

        editMenu.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.editMenu.text")); // NOI18N
        jMenuBar1.add(editMenu);

        blastMenu.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.blastMenu.text")); // NOI18N

        blastnMenuItem.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.blastnMenuItem.text")); // NOI18N
        blastnMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blastnMenuItemActionPerformed(evt);
            }
        });
        blastMenu.add(blastnMenuItem);

        blast2seqMenuItem.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.blast2seqMenuItem.text")); // NOI18N
        blast2seqMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blast2seqMenuItemActionPerformed(evt);
            }
        });
        blastMenu.add(blast2seqMenuItem);

        exportMenuItem.setText(org.openide.util.NbBundle.getMessage(blastoGUI.class, "blastoGUI.exportMenuItem.text")); // NOI18N
        exportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportMenuItemActionPerformed(evt);
            }
        });
        blastMenu.add(exportMenuItem);

        jMenuBar1.add(blastMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seq1OpenButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seq1ImportButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seq1NameTextField))
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seq2OpenButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seq2ImportButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seq2NameTextField))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(blastnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(blast2seqButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(exportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(outputNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(seq1OpenButton)
                    .addComponent(seq1ImportButton)
                    .addComponent(seq2OpenButton)
                    .addComponent(seq2ImportButton)
                    .addComponent(seq1NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seq2NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(blastnButton)
                        .addGap(18, 18, 18)
                        .addComponent(blast2seqButton)
                        .addGap(18, 18, 18)
                        .addComponent(exportButton))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seq1OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seq1OpenMenuItemActionPerformed
        int returnVal = fc.showOpenDialog(blastoGUI.this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            blastoIO.importFromFile(file, seq1TextArea, seq1NameTextField);
        }
    }//GEN-LAST:event_seq1OpenMenuItemActionPerformed

    private void seq1ImportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seq1ImportMenuItemActionPerformed
        blastoIO.importFromClotho(seq1TextArea, seq1NameTextField);
    }//GEN-LAST:event_seq1ImportMenuItemActionPerformed

    private void seq2OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seq2OpenMenuItemActionPerformed
        int returnVal = fc.showOpenDialog(blastoGUI.this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            blastoIO.importFromFile(file, seq2TextArea, seq2NameTextField);
        }
    }//GEN-LAST:event_seq2OpenMenuItemActionPerformed

    private void seq2ImportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seq2ImportMenuItemActionPerformed
        blastoIO.importFromClotho(seq2TextArea, seq2NameTextField);
    }//GEN-LAST:event_seq2ImportMenuItemActionPerformed

    private void blastnMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blastnMenuItemActionPerformed
        String inputSeq = seq1TextArea.getText().replace(System.getProperty("line.separator"), "");
        inputSeq = inputSeq.replaceAll("\\s", "");
        jProgressBar1.setIndeterminate(true);
        blastoTask task = new blastoTask(inputSeq, blastTextArea);
        task.addPropertyChangeListener(
                new PropertyChangeListener() {
            @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        if ("progress".equals(evt.getPropertyName())) {
                            int progress = (Integer) evt.getNewValue();
                            jProgressBar1.setIndeterminate(false);
                            jProgressBar1.setValue(progress);
                        }
                    }
                });
        task.execute();
        //blastoBLAST.blastn(inputSeq, blastTextArea);
        outputNameTextField.setText(seq1NameTextField.getText() + "_results.txt");
    }//GEN-LAST:event_blastnMenuItemActionPerformed

    private void blast2seqMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blast2seqMenuItemActionPerformed
        String inputSeq1 = seq1TextArea.getText().replace(System.getProperty("line.separator"), "");
        inputSeq1 = inputSeq1.replaceAll("\\s", "");
        String inputSeq2 = seq2TextArea.getText().replace(System.getProperty("line.separator"), "");
        inputSeq2 = inputSeq2.replaceAll("\\s", "");
        jProgressBar1.setIndeterminate(true);
        blastoTask task = new blastoTask(inputSeq1, inputSeq2, blastTextArea);
        task.addPropertyChangeListener(
                new PropertyChangeListener() {
            @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        if ("progress".equals(evt.getPropertyName())) {
                            int progress = (Integer) evt.getNewValue();
                            jProgressBar1.setIndeterminate(false);
                            jProgressBar1.setValue(progress);
                        }
                    }
                });
        task.execute();
        //blastoBLAST.blast2seq(inputSeq1, inputSeq2, blastTextArea);
        outputNameTextField.setText(seq1NameTextField.getText() + "_" + seq2NameTextField.getText() + "_results.txt");
    }//GEN-LAST:event_blast2seqMenuItemActionPerformed

    private void exportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportMenuItemActionPerformed
        fc.setSelectedFile(new File(outputNameTextField.getText()));
        int returnVal = fc.showSaveDialog(blastoGUI.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            File file = fc.getSelectedFile();
            try {
                blastoIO.exportToFile(file, blastTextArea);
            } catch (Exception exception) {
            }
        }
    }//GEN-LAST:event_exportMenuItemActionPerformed

    private void seq1OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seq1OpenButtonActionPerformed
        seq1OpenMenuItemActionPerformed(evt);
    }//GEN-LAST:event_seq1OpenButtonActionPerformed

    private void seq1ImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seq1ImportButtonActionPerformed
        seq1ImportMenuItemActionPerformed(evt);
    }//GEN-LAST:event_seq1ImportButtonActionPerformed

    private void seq2OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seq2OpenButtonActionPerformed
        seq2OpenMenuItemActionPerformed(evt);
    }//GEN-LAST:event_seq2OpenButtonActionPerformed

    private void seq2ImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seq2ImportButtonActionPerformed
        seq2ImportMenuItemActionPerformed(evt);
    }//GEN-LAST:event_seq2ImportButtonActionPerformed

    private void blastnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blastnButtonActionPerformed
        blastnMenuItemActionPerformed(evt);
    }//GEN-LAST:event_blastnButtonActionPerformed

    private void blast2seqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blast2seqButtonActionPerformed
        blast2seqMenuItemActionPerformed(evt);
    }//GEN-LAST:event_blast2seqButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        exportMenuItemActionPerformed(evt);
    }//GEN-LAST:event_exportButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blast2seqButton;
    private javax.swing.JMenuItem blast2seqMenuItem;
    private javax.swing.JMenu blastMenu;
    private javax.swing.JTextArea blastTextArea;
    private javax.swing.JButton blastnButton;
    private javax.swing.JMenuItem blastnMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton exportButton;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField outputNameTextField;
    private javax.swing.JButton seq1ImportButton;
    private javax.swing.JMenuItem seq1ImportMenuItem;
    private javax.swing.JMenu seq1Menu;
    private javax.swing.JTextField seq1NameTextField;
    private javax.swing.JButton seq1OpenButton;
    private javax.swing.JMenuItem seq1OpenMenuItem;
    private javax.swing.JTextArea seq1TextArea;
    private javax.swing.JButton seq2ImportButton;
    private javax.swing.JMenuItem seq2ImportMenuItem;
    private javax.swing.JMenu seq2Menu;
    private javax.swing.JTextField seq2NameTextField;
    private javax.swing.JButton seq2OpenButton;
    private javax.swing.JMenuItem seq2OpenMenuItem;
    private javax.swing.JTextArea seq2TextArea;
    // End of variables declaration//GEN-END:variables
    final javax.swing.JFileChooser fc;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
}
