/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.clothocad.viewer.partviewertc;

import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JScrollPane;
import org.clothocad.viewer.partviewertc.panels.VisualScene;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.clothocad.viewer.partviewertc//ImageWindow//EN",
autostore = false)
public final class ImageWindowTopComponent extends TopComponent {

    private static ImageWindowTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "ImageWindowTopComponent";

    public ImageWindowTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ImageWindowTopComponent.class, "CTL_ImageWindowTopComponent"));
        setToolTipText(NbBundle.getMessage(ImageWindowTopComponent.class, "HINT_ImageWindowTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroller = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(scroller, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scroller;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized ImageWindowTopComponent getDefault() {
        if (instance == null) {
            instance = new ImageWindowTopComponent();
        }
        return instance;
    }

    public JScrollPane getScroller() {
        return scroller;
    }
    /**
     * Obtain the ImageWindowTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized ImageWindowTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(ImageWindowTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof ImageWindowTopComponent) {
            return (ImageWindowTopComponent) win;
        }
        Logger.getLogger(ImageWindowTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    private JComponent myView;
}
