/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewFrame.java
 *
 * Created on Aug 19, 2012, 9:55:22 AM
 */
package org.clothocad.tool.pigeongenerator;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import org.clothocore.api.core.Collector;
import org.clothocore.api.data.Collection;
import org.clothocore.api.data.ObjBase;
import org.clothocore.api.data.ObjType;
import org.clothocore.api.data.Part;
import org.openide.util.Exceptions;

/**
 *
 * @author jenhan
 */
public class ViewFrame extends javax.swing.JFrame {

    /** Creates new form ViewFrame */
    public ViewFrame() {
        initComponents();
        jLabel1.setText("Select a Collection");
        jButton1.setText("Generate Pigeon");
        jComboBox1.removeAllItems();
        ArrayList allCollections = Collector.getAll(ObjType.COLLECTION);

        for (Object c : allCollections) {
            jComboBox1.addItem(((Collection) c).getName());
        }
        _loadedGUI = true;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Part Name", "Format", "Composition"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(ViewFrame.class, "ViewFrame.jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(ViewFrame.class, "ViewFrame.jTable1.columnModel.title1")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(ViewFrame.class, "ViewFrame.jTable1.columnModel.title2_1")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ViewFrame.class, "ViewFrame.jLabel1.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(ViewFrame.class, "ViewFrame.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, 0, 376, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   System.out.println("selected collection: " + jComboBox1.getSelectedItem());
    if (jComboBox1.getSelectedItem() != null && _loadedGUI) {
        for (int i = 0; i < jTable1.getModel().getRowCount(); i++) {
            ((DefaultTableModel) jTable1.getModel()).removeRow(0);
        }
        Collection selectedCollection = Collection.retrieveByName((String) jComboBox1.getSelectedItem());
        HashSet<String> all = selectedCollection.recursiveGetAllLinksOf(ObjType.PART);
        List<String> allPartNames = new ArrayList<String>();
        for (String link : all) {
            Part p = Collector.getPart(link);
            System.out.println("looking at part: " + p.getName());
            if (p.getPartType().equals(Part.partType.Composite)) {
                allPartNames.add(p.getName());
                    ArrayList<Part> partComposition;
                    ArrayList<String> composition = new ArrayList();
                    try {
                        partComposition = controller.getComposition(p);
                        for(Part aPart:partComposition) {
                        composition.add(aPart.getName());
                    }
                    } catch (Exception ex) {
                        Exceptions.printStackTrace(ex);
                    }
                    
                ((DefaultTableModel) jTable1.getModel()).addRow(new Object[]{p.getName(),p.getFormat().getName(), composition});

            }
        }
    }
    
    
    
}//GEN-LAST:event_jComboBox1ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int[] selectedIndices = jTable1.getSelectedRows();

    if (selectedIndices.length > 0) {
        for (int i = 0; i < selectedIndices.length; i++) {
            int index = selectedIndices[i];
            String currentName = (String) jTable1.getModel().getValueAt(index, 0);
            controller.postPigeon(currentName);
        }

    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
}//GEN-LAST:event_jComboBox1ItemStateChanged

private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
   System.out.println("selected collection: " + jComboBox1.getSelectedItem());
    if (jComboBox1.getSelectedItem() != null && _loadedGUI) {
        for (int i = 0; i < jTable1.getModel().getRowCount(); i++) {
            ((DefaultTableModel) jTable1.getModel()).removeRow(0);
        }
        Collection selectedCollection = Collection.retrieveByName((String) jComboBox1.getSelectedItem());
        HashSet<String> all = selectedCollection.recursiveGetAllLinksOf(ObjType.PART);
        List<String> allPartNames = new ArrayList<String>();
        for (String link : all) {
            Part p = Collector.getPart(link);
            System.out.println("looking at part: " + p.getName());
            if (p.getPartType().equals(Part.partType.Composite)) {
                allPartNames.add(p.getName());
                ((DefaultTableModel) jTable1.getModel()).addRow(new Object[]{p.getName(),"Moo", "thecow"});

            }
        }
    }


}//GEN-LAST:event_jComboBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ViewFrame().setVisible(true);
            }
        });
    }
    private boolean _loadedGUI;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
